<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DegraChat.Overlay.Engine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DegraChat.Core\DegraChat.Core.csproj" />
    <PackageReference Include="Scriban" Version="5.12.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>
</Project>
